### PR TITLE
Adapt requirements

### PR DESCRIPTION
**Pull request by FinalAngel**
to be aligned with aldryn-newsblog

### CODE REVIEW

**Comment by intellectronica** [comment]
:+1:

**Comment by mkoistinen** [comment]
Why are tests no longer passing?

**Comment by mkoistinen** [comment]
Why did you remove django-admin-sortable AND the note to say why it is there in the first place?

**Comment by mkoistinen** [comment]
:-1:

**Comment by FinalAngel** [comment]
nope to risky - closing

**Pull request closed without merging**
