### PR TITLE
88% Test Coverage, Py2/3 compatibility

### PR DESCRIPTION
**Pull request by mkoistinen**

### CODE REVIEW

**Comment by mkoistinen** [comment]
@czpython I would like to commit this onto Master. Would it be possible for you to deploy `develop` into a real project to ensure that it still works as it should?

**Comment by czpython** [comment]
@mkoistinen the only project that comes to mind is the standard site. @FinalAngel is it ok with you to deploy this latest version there ?

**Comment by FinalAngel** [comment]
@czpython well I think with the template changes to bootstrap the backwards compatibility might be broken?

**Comment by czpython** [comment]
Yes it would be but I don't think we have much choice there..

**Pull request closed without merging**
