### PR TITLE
Proper migration setup

### PR DESCRIPTION
**Pull request by FinalAngel**
- rename ``migrations_django`` to ``south_migrations``
- recompile ``migrations`` to be save

### CODE REVIEW

**Comment by mkoistinen** [comment]
LGTM

**Comment by mkoistinen** [comment]
Hmmm, looks like Travis doesn't like it.

**Comment by FinalAngel** [comment]
actually the same happens here @mkoistinen https://github.com/aldryn/aldryn-faq/pull/61

**Comment by FinalAngel** [comment]
Apparently the tests did not work on the latest releases of ckeditor or the cms, should be fixed now @mkoistinen

**Comment by mkoistinen** [comment]
Super, lgtm

**Pull request merged**
