### PR TITLE
Simplify templates

### PR DESCRIPTION
**Pull request by FinalAngel**
The goal of this Pull Request is:

- Simplify template structure
- Remove unnecessary placeholder and blocks
- In general make everything simple for easier explanation

We also want to remove ``render_placeholder view.config`` and later only mention it in the documentation (separate PR will follow).

### CODE REVIEW

**Comment by vxsx** [comment]
is it correct that landing template doesn't load category list anymore? (we would need to invest more time in rewriting tests to add correct plugin etc)

**Comment by FinalAngel** [comment]
@vxsx we should probably still include the category list template in the landing page as an example. What do you think?

**Comment by vxsx** [comment]
i say we should

**Comment by lory87** [comment]
lgtm

**Comment by vxsx** [comment]
:+1:

**Pull request merged**
