### PR TITLE
fix cms plugin table names

### PR DESCRIPTION
**Pull request by Chive**
now also includes cms3.1 compat

### CODE REVIEW

**Comment by stefanfoulis** [comment]
LGTM

**Comment by mkoistinen** [comment]
I think you have to be more defensive about all of this, or it won't work in CMS 3.1 installs.

**Comment by Chive** [comment]
As discussed with @mkoistinen I nulled @czpython's migration #0007 to ensure cms 3.1 compat

**Comment by czpython** [comment]
As mentioned to @Chive this migration (7) actually worked on versions less than 3.1, so was this tested on versions less than 3.1? does migrating there work? /cc @mkoistinen

**Comment by Chive** [comment]
Yes. Tested on pre 3, 3.0 and 3.1 @czpython :)

**Comment by mkoistinen** [comment]
Yes, this is the same technique used by django-filer and is tested to work for all recent versions of CMS (>2.0).

**Comment by mkoistinen** [comment]
:+1:

**Pull request merged**
