### PR TITLE
Added faq block creation and question deletion tests

### PR DESCRIPTION
**Pull request by Marketionist**
**This pull request adds faq block creation and question deletion tests**

Also:
- updated ```return```
- **known issue**: phantomjs fails for Aldryn FAQ tests: creates a new question - apparently because of iframe switching. Works ok on Chrome and Firefox
- **known issue**: some tests will fail as ```aldryn_apphook_reload``` is not configured yet

### CODE REVIEW

**Comment by FinalAngel** [comment]
looks good, but the deep nesting is again a bit tricky

**Comment by vxsx** [comment]
:+1:

**Comment by vxsx** [comment]
:+1: as long as the travis passes

**Comment by Marketionist** [comment]
Travis will not pass as long as ```aldryn_apphook_reload``` will not be added/configured. @mkoistinen please have a look

**Pull request merged**
